services:
  - type: web
    name: url-shortener
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        generateValue: true
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 30
      - key: RATE_LIMIT_WINDOW_MS
        value: 86400000
      - key: SHORT_CODE_LENGTH
        value: 6
      - key: MONGODB_URI_0
        sync: false
      - key: REDIS_URL
        sync: false 